In [4]:
import pandas as pd

In [14]:
pd.__version__

'2.3.1'

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [7]:
df.max()

engine_displacement                  380
num_cylinders                       13.0
horsepower                         271.0
vehicle_weight               4739.077089
acceleration                        24.3
model_year                          2023
origin                               USA
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                            4.0
fuel_efficiency_mpg            25.967222
dtype: object

In [310]:
df.shape
df.index

RangeIndex(start=0, stop=9704, step=1)

In [11]:
df['fuel_type'].nunique(0)

2

In [329]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [323]:
asia_only = df[df['origin']=='Asia']

In [324]:
asia_with_fuel_efficiency_mpg  = asia_only[['origin', 'fuel_efficiency_mpg']]

In [325]:
max_fuel_efficiency = asia_with_fuel_efficiency_mpg .max()

In [176]:
max_fuel_efficiency

origin                      Asia
fuel_efficiency_mpg    23.759123
dtype: object

In [122]:
median = df.horsepower.median()

In [123]:
median

np.float64(149.0)

In [101]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [135]:
df.horsepower[df.horsepower.isnull()]

3      NaN
5      NaN
11     NaN
60     NaN
65     NaN
        ..
9587   NaN
9625   NaN
9628   NaN
9635   NaN
9688   NaN
Name: horsepower, Length: 708, dtype: float64

In [144]:
replace_null = df['horsepower'].fillna(median)

In [147]:
replace_null.median()

np.float64(149.0)

In [145]:
df.horsepower.median()

np.float64(149.0)

In [163]:
asia_only

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [167]:
asia_only[['vehicle_weight', 'model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [177]:
asia_only[['vehicle_weight', 'model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [178]:
x = asia_only[['vehicle_weight', 'model_year']].head(7).values

In [179]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [182]:
import numpy as np

In [330]:
XT = x.T

In [331]:
XT
# shape (2. 7)

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [358]:
XTX = x.T @ x

In [359]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [360]:
invert_XTX = np.linalg.inv(XTX)

In [366]:
invert_XTX
np.set_printoptions(suppress=True)
print(np.round(invert_XTX, 4))

[[ 0. -0.]
 [-0.  0.]]


In [374]:
y = np.array([ [1100, 1300, 800, 900, 1000, 1100, 1200]], dtype=float)
assert y.size == x.shape[0]
print("y shape:", y.shape)

y shape: (1, 7)


In [376]:
w = invert_XTX @ x.T @ y
w_rounded = [rounde(float(v), 2) for v in w]
print("w: ", w_rounded)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 7)

In [345]:
w.sum()

np.float64(1.9999999999999933)

In [300]:
x.shape, y.shape

((7, 2), (1, 7))